import streamlit as st
import random as r

study_tips = [
    # Active Learning & Retention
    "Use active recall by testing yourself with flashcards or closed-book quizzes instead of passively re-reading.",
    "Apply the Feynman Technique: explain complex concepts in plain language as if teaching a 10-year-old.",
    "Practice the Blurting Method: read a topic, hide the material, and write down everything you remember.",
    "Use spaced repetition tools like Anki to review information at expanding time intervals.",
    "Teach what you learn to a study partner, classmate, or even an imaginary audience.",
    "Turn textbook headings into questions and read specifically to answer them.",
    "Practice 'dual coding' by pairing written text with visual diagrams or sketches.",
    "Solve practice problems from scratch without looking at the step-by-step solutions first.",
    "Create your own original practice quiz questions after finishing a chapter.",
    "Work through sample math or science problems backwards from the answer to understand key mechanisms.",
    "Rephrase definitions and core concepts in your own words rather than copying text verbatim.",
    "Use comparison tables when studying contrasting theories, models, or historical eras.",
    "Practice mental rehearsal and visualization before high-stakes exams or presentations.",
    "Convert dense lecture slides into blank fill-in-the-blank worksheets for review.",
    "Write a concise 50-word summary for lengthy articles or chapter sections.",

    # Time Management & Productivity
    "Use the Pomodoro Technique: study uninterrupted for 25 minutes, then take a 5-minute break.",
    "Implement 50-minute study blocks followed by 10-minute full-rest breaks.",
    "Use the 5-Minute Rule: commit to working on an intimidating task for just 5 minutes to overcome initial friction.",
    "Prioritize daily tasks using the Eisenhower Matrix (Urgent vs. Important).",
    "Tackle your hardest or most intimidating task first thing in the day (Eat the Frog).",
    "Time-block your study sessions on a Google Calendar or physical planner.",
    "Set a strict, non-negotiable daily stop time for studying to prevent burnout and protect rest.",
    "Batch administrative tasks (responding to emails, organizing files) into a single 20-minute daily block.",
    "Set specific, measurable goals for every individual study block (e.g., 'complete 10 problems').",
    "Limit your primary daily study priorities to no more than 3 key deliverables.",
    "Track your raw study hours per subject to ensure a balanced workload distribution.",
    "Anchor new study habits to existing routines (e.g., review flashcards for 10 minutes right after morning coffee).",
    "Cross off completed items on paper to trigger a psychological sense of progress.",
    "Build a weekly study schedule every Sunday night to set clear expectations.",
    "Use visual timers to build stronger time awareness and prevent time distortion.",

    # Focus & Environment Setup
    "Keep your smartphone in another room or inside a drawer while studying.",
    "Establish a dedicated study space used exclusively for learning to prime your brain for focus.",
    "Clear your physical desk of all visual clutter before opening your books.",
    "Use website and app blockers like Forest, Freedom, or Cold Turkey during work blocks.",
    "Keep a 'distraction log' notepad nearby to write down non-study thoughts for later action.",
    "Block out intrusive ambient noise using lo-fi beats, classical music, or brown noise without lyrics.",
    "Keep your study space slightly cool to maintain high alertness and prevent drowsiness.",
    "Ensure your study area is well-lit to reduce eye strain and fatigue.",
    "Vary your study locations occasionally (e.g., library, coffee shop) to build varied contextual memory anchors.",
    "Avoid studying on or in your bed to maintain a clear boundary between work and sleep.",
    "Establish a pre-study ritual (e.g., clearing the desk, pouring water) to signal focus time.",
    "Set clear boundaries with housemates or family regarding your uninterrupted focus hours.",
    "Wear comfortable, non-restrictive clothing during long study sessions.",
    "Keep healthy, non-greasy focus snacks (e.g., nuts, berries) near your workspace.",
    "Keep dirty dishes, food waste, and unrelated clutter away from your workspace.",

    # Note-Taking Strategies
    "Organize lecture notes using the Cornell Note-Taking System (cues, notes, summary).",
    "Take handwritten notes during primary lectures for higher conceptual retention and synthesis.",
    "Create mind maps to visualize connections and hierarchies across broad topic areas.",
    "Use a consistent color-coding scheme across all subjects (e.g., green for definitions, blue for formulas).",
    "Use highlighters sparingly—focus only on key phrases, never entire sentences.",
    "Leave generous white space or double-space notes to allow room for later additions.",
    "Write bulleted takeaways at the bottom of every page of handwritten notes.",
    "Maintain a dedicated 'Mistakes Notebook' tracking every question you miss and why.",
    "Summarize an entire 50-minute lecture in three clear, high-level bullet points.",
    "Create a master cheat-sheet covering all major formulas and key principles for a subject.",
    "Use standard abbreviations and shorthand to write faster during live lectures.",
    "Review and annotate your lecture notes within 24 hours to dramatically slow forgetting.",
    "Use sticky page-flags to mark critical sections in physical textbooks.",
    "Record audio dumps of key summary points on your phone to listen back to later.",
    "Keep a scratch notebook dedicated strictly to quick brainstorms and working memory calculations.",

    # Exam Preparation & Test-Taking
    "Analyze past exam papers under timed conditions to get used to the format and pacing.",
    "Review syllabus learning objectives to ensure you focus on what instructors value most.",
    "Analyze common question structures and phrasing patterns in past quizzes.",
    "Solve practice exams without consulting notes to uncover your true knowledge gaps.",
    "Use red ink strictly for self-correction on practice tests to make errors visually distinct.",
    "Read through all test instructions and questions carefully before answering a single prompt.",
    "Answer easy and high-confidence test questions first to build momentum and bank points.",
    "Underline or highlight key terms in essay prompts (e.g., 'compare', 'contrast', 'evaluate').",
    "Practice answering short-answer and essay prompts under strict time limits.",
    "Double-check test dates, room locations, and logistics at least two days in advance.",
    "Avoid cramming the night before an exam; prioritize sleep for memory consolidation.",
    "Review previous graded work and instructor feedback carefully before submitting new tasks.",
    "Arrive early to exam rooms to settle in and perform a brief deep-breathing exercise.",
    "Write down key formulas or memory triggers on scratch paper as soon as the test begins.",
    "Do a final sweep of your completed exam to catch simple calculation or reading errors.",

    # Memory Systems & Mnemonics
    "Use acronyms and initialisms to memorize lists and ordered sequences.",
    "Build acrostics (sentences where each word starts with a specific letter) for tricky series.",
    "Use the Method of Loci (Memory Palace) to associate list items with spatial locations in a familiar room.",
    "Group or 'chunk' individual pieces of information into meaningful 3- to 5-item clusters.",
    "Use the Leitner Box System to systematically cycle flashcard reviews based on mastery.",
    "Create vivid, exaggerated, or funny mental images to anchor abstract terms.",
    "Rhyme key formulas or facts to leverage auditory memory pathways.",
    "Group flashcards by conceptual category rather than arbitrary chapter numbers.",
    "Review high-difficulty flashcards right before going to sleep to maximize overnight consolidation.",
    "Keep flashcards focused on a single concise question and answer per card.",

    # Health, Energy & Mindset
    "Prioritize 7 to 9 hours of quality sleep every night to consolidate newly formed memories.",
    "Stay hydrated throughout the day; mild dehydration impairs cognitive processing and focus.",
    "Avoid caffeine intake within 6 hours of bedtime to preserve deep sleep architecture.",
    "Expose your eyes to natural daylight early in the morning to keep your circadian rhythm locked.",
    "Engage in light aerobic movement or stretching during study breaks to boost cerebral blood flow.",
    "Practice Box Breathing (4s in, 4s hold, 4s out, 4s hold) to reduce stress and anxiety.",
    "Eat nutrient-dense foods rich in complex carbs, healthy fats, and antioxidants.",
    "Take a 20-minute power nap in the early afternoon if experiencing severe cognitive fatigue.",
    "Exercise self-compassion when a study session goes poorly; focus on long-term consistency over perfection.",
    "Incorporate deliberate physical rest with no screens during short study breaks.",
    "Connect abstract study concepts to real-world applications to maintain intrinsic motivation.",
    "Celebrate small milestones and completed task blocks to sustain dopamine and drive.",
    "Sit with proper posture in an ergonomic chair to prevent physical strain and energy slumps.",
    "Avoid multi-tasking completely; context switching severely taxes cognitive resources.",
    "Keep non-academic worries off your mind by journaling for 5 minutes before studying.",

    # Digital Tools & Workflow
    "Use structured note apps like Notion, Obsidian, or OneNote for interlinked subject archives.",
    "Standardize folder and file-naming formats across all your devices for fast searching.",
    "Master keyboard shortcuts for your primary note-taking software to eliminate friction.",
    "Convert lecture slide decks into searchable PDFs for instant keyword lookups.",
    "Use text-to-speech tools to listen to long reading assignments while walking or commuting.",
    "Use voice-to-text dictation to quickly brain-dump essay outlines and initial thoughts.",
    "Back up all academic notes and critical papers automatically to a secure cloud service.",
    "Use dark mode or high-contrast screen settings to minimize digital eye strain.",
    "Keep browser tab counts low by bookmarking or saving articles into read-later tools.",
    "Use digital sticky notes on your desktop for high-priority reminders and deadlines.",

    # Reading & Comprehension
    "Use the SQ3R method: Survey, Question, Read, Recite, and Review.",
    "Read the chapter summary and review questions *before* reading the actual main text.",
    "Read aloud when struggling through dense, abstract, or difficult paragraphs.",
    "Look up unfamiliar domain terminology immediately in a specialized subject glossary.",
    "Pace your reading speed visually using a pen, finger, or pointer along the page.",
    "Break lengthy textbook chapters into smaller 5-page reading sprints.",
    "Skim the table of contents and main subheadings to grasp the macro outline before deep reading.",
    "Write quick margin notes summarizing the main takeaway of each paragraph.",
    "Pay close attention to bold words, italicized terms, and callout boxes in textbooks.",
    "Synthesize multiple reading sources into a single master summary topic sheet.",

    # Study Group Strategies
    "Form study groups of 3 to 4 dedicated peers with clear, predefined session agendas.",
    "Assign specific presentation topics to each group member prior to meeting.",
    "Use group study sessions primarily for testing each other and debating complex points.",
    "Keep study group meetings strictly time-boxed to prevent them from becoming social hours.",
    "Create shared online document banks for collaborative past-paper answer keys.",

    # Ergonomics & Physical Habits
    "Follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds.",
    "Position monitor screens 20 to 26 inches away from your eyes at eye level.",
    "Alternate between sitting and using a standing desk setup to sustain energy levels.",
    "Perform gentle neck and wrist stretches after every hour of continuous typing.",
    "Keep a refilled water bottle sitting right on your desk within arm's reach.",

    # Advanced Learning Habits
    "Interleave your learning by switching between related sub-topics within a single study block.",
    "Focus on deeply understanding core underlying principles before memorizing details.",
    "Bridge new knowledge to existing concepts you already understand using analogies.",
    "Review new concepts periodically over weeks rather than block-cramming them over days.",
    "Reflect on what study methods worked best after every exam cycle and adjust accordingly.",
    "Break large term projects down into small outline, draft, and edit sub-tasks across multiple days.",
    "Consult your professors or teaching assistants during office hours early when stuck.",
    "Keep a running log of essential definitions and formulas organized alphabetically.",
    "Avoid studying two visually or conceptually similar subjects back-to-back.",
    "Focus relentless attention on quality, high-intensity study over total raw hours sitting down."
]

random_facts = [
    "Honey can remain edible for extremely long periods when properly stored.",
    "Octopuses have three hearts.",
    "Bananas are botanically classified as berries.",
    "Strawberries are not botanically classified as true berries.",
    "A day on Venus is longer than a year on Venus.",
    "The Moon is slowly moving away from Earth.",
    "Lightning can heat the surrounding air to temperatures hotter than the surface of the Sun.",
    "Water expands when it freezes.",
    "Sound travels faster through water than through air.",
    "The Pacific Ocean is the largest ocean on Earth.",
    "Earth is not a perfect sphere; it is slightly flattened at the poles.",
    "Jupiter is the largest planet in our Solar System.",
    "Saturn's rings are made mostly of ice and rocky particles.",
    "Mars has the largest volcano known in the Solar System.",
    "The Sun contains more than 99% of the mass of the Solar System.",
    "A light-year measures distance, not time.",
    "The speed of light in a vacuum is about 300,000 kilometers per second.",
    "The Milky Way contains billions of stars.",
    "Earth's atmosphere is mostly nitrogen.",
    "Plants release oxygen during photosynthesis.",
    "Some bamboo species can grow remarkably quickly under ideal conditions.",
    "Trees can communicate chemically through underground fungal networks.",
    "Some plants can trap insects for nutrients.",
    "Venus is the hottest planet in the Solar System.",
    "Mercury has extreme temperature differences between day and night.",
    "Neptune has extremely fast winds.",
    "Uranus rotates on its side compared with most planets.",
    "The Great Red Spot on Jupiter is a massive storm.",
    "The Moon has no substantial atmosphere like Earth's.",
    "Footprints on the Moon can remain for a very long time because there is almost no wind.",
    "Sharks existed before trees appeared on Earth.",
    "Crows can recognize individual human faces.",
    "Dolphins use distinctive whistles that can function like names.",
    "Elephants can communicate using sounds below the range of human hearing.",
    "Giraffes and humans have the same number of neck vertebrae: seven.",
    "A group of flamingos is called a flamboyance.",
    "Koalas have fingerprints that can resemble human fingerprints.",
    "Sea otters sometimes hold hands while sleeping.",
    "Penguins cannot fly, but they are excellent swimmers.",
    "Bees can communicate the location of food through a waggle dance.",
    "Butterflies taste using receptors on their feet.",
    "Some frogs can survive being partially frozen.",
    "Hummingbirds can fly backward.",
    "Owls cannot move their eyes like humans do.",
    "A snail can have thousands of tiny teeth-like structures.",
    "Jellyfish have existed for hundreds of millions of years.",
    "Some turtles can breathe through specialized tissues while underwater.",
    "Blue whales are the largest animals known to have lived.",
    "A blue whale's heart is extremely large.",
    "The human brain uses a significant amount of the body's energy.",
    "The human skeleton contains 206 bones in a typical adult.",
    "Babies are born with more bones than adults.",
    "The smallest bone in the human body is the stapes in the ear.",
    "The largest bone in the human body is the femur.",
    "Your skin is the body's largest organ.",
    "Humans produce saliva to help begin digestion.",
    "The human heart beats millions of times each year.",
    "Red blood cells carry oxygen around the body.",
    "White blood cells help defend the body against pathogens.",
    "The lungs contain millions of tiny air sacs called alveoli.",
    "The human body contains trillions of microorganisms.",
    "Your fingerprints develop before birth.",
    "The tongue contains many muscles working together.",
    "Humans can distinguish millions of different colors.",
    "The cornea gets oxygen directly from the air.",
    "Your brain itself does not contain pain receptors.",
    "The average adult human body is mostly water by mass.",
    "DNA contains instructions used by living organisms to build and maintain cells.",
    "DNA has a double-helix structure.",
    "Humans share much of their DNA with other living organisms.",
    "Cells are the basic structural units of living organisms.",
    "Some organisms consist of only one cell.",
    "Bacteria can be found almost everywhere on Earth.",
    "Some bacteria are beneficial to humans.",
    "Viruses are much smaller than most bacteria.",
    "Mitochondria are often called the powerhouses of cells.",
    "Red blood cells do not normally contain a nucleus in humans.",
    "Plants have cells with rigid cell walls.",
    "Chlorophyll helps plants capture light energy.",
    "Photosynthesis converts light energy into chemical energy.",
    "Fungi are more closely related to animals than to plants.",
    "Mushrooms are the reproductive structures of some fungi.",
    "Yeast is a type of fungus.",
    "Lichens are partnerships between fungi and photosynthetic organisms.",
    "Coral reefs are built by tiny animals called coral polyps.",
    "Some corals have symbiotic relationships with algae.",
    "The Amazon rainforest is one of the most biodiverse regions on Earth.",
    "The Sahara is the largest hot desert in the world.",
    "Antarctica is the largest desert on Earth by precipitation.",
    "Antarctica contains most of Earth's freshwater ice.",
    "Mount Everest is the highest mountain above sea level.",
    "The Mariana Trench contains the deepest known parts of Earth's oceans.",
    "Earth's tectonic plates are constantly moving.",
    "Volcanoes can create new land.",
    "Earthquakes are caused by movements in Earth's crust.",
    "The water cycle moves water between Earth's surface and atmosphere.",
    "Clouds are made of tiny water droplets or ice crystals.",
    "Snowflakes form with six-sided symmetry.",
    "Rainbows result from light being refracted, reflected, and dispersed in water droplets.",
    "A prism can separate white light into different colors.",
    "Objects fall toward Earth because of gravity.",
    "Mass and weight are different physical quantities.",
    "Energy cannot be created or destroyed in an isolated system.",
    "Matter is made of atoms.",
    "Atoms contain protons, neutrons, and electrons.",
    "Protons have a positive electric charge.",
    "Electrons have a negative electric charge.",
    "Neutrons have no electric charge.",
    "Electric current is the flow of electric charge.",
    "Magnets have north and south poles.",
    "Like magnetic poles repel each other.",
    "Opposite magnetic poles attract each other.",
    "Copper is a good conductor of electricity.",
    "Rubber is generally a poor conductor of electricity.",
    "Glass can be transparent to visible light.",
    "Diamonds are made of carbon.",
    "Graphite and diamond are different forms of carbon.",
    "The periodic table organizes chemical elements.",
    "Hydrogen is the lightest chemical element.",
    "Oxygen supports combustion.",
    "Carbon dioxide is a gas produced by respiration and combustion.",
    "Water is made of hydrogen and oxygen.",
    "Salt commonly used in food is sodium chloride.",
    "The pH scale describes how acidic or basic a solution is.",
    "A neutral aqueous solution has a pH close to 7 at standard conditions.",
    "Boiling point changes with atmospheric pressure.",
    "Water boils at a lower temperature at high altitude.",
    "Ice is less dense than liquid water.",
    "Some metals are liquid near room temperature.",
    "Mercury is a metal that is liquid at typical room temperatures.",
    "Iron is one of the most abundant elements in Earth.",
    "Rust forms when iron reacts with oxygen and moisture.",
    "The wheel is one of the oldest important inventions.",
    "Paper was invented in ancient China.",
    "The printing press helped spread books widely in Europe.",
    "The first programmable electronic computers were developed in the 20th century.",
    "Binary uses only two digits: 0 and 1.",
    "A byte commonly contains eight bits.",
    "HTML is used to structure web pages.",
    "CSS is used to style web pages.",
    "Python was named after Monty Python, not the snake.",
    "The first version of Python was released in the early 1990s.",
    "C++ was developed as an extension of the C programming language.",
    "Algorithms are step-by-step procedures for solving problems.",
    "A database is designed to store and organize information.",
    "Artificial intelligence can be used for tasks such as classification and prediction.",
    "Machine learning is a branch of artificial intelligence.",
    "Neural networks are inspired loosely by biological nervous systems.",
    "A computer CPU performs instructions and calculations.",
    "RAM is used for temporary working data.",
    "A hard drive or SSD can store data even when a computer is turned off.",
    "An SSD has no spinning magnetic disks.",
    "Wi-Fi uses radio waves to communicate data wirelessly.",
    "GPS uses signals from satellites to determine location.",
    "The internet is a global network of interconnected networks.",
    "The World Wide Web is a service that operates over the internet.",
    "The first successful powered airplane flight was made by the Wright brothers in 1903.",
    "The Eiffel Tower was completed in 1889.",
    "The Great Wall of China is made from many different sections and materials.",
    "The ancient Egyptians used a form of writing called hieroglyphics.",
    "The Roman Colosseum was built in ancient Rome.",
    "The Olympic Games originated in ancient Greece.",
    "The word 'alphabet' comes from the first two Greek letters, alpha and beta.",
    "A leap year usually has 366 days.",
    "A standard week has seven days.",
    "A triangle has three sides.",
    "A square has four equal sides.",
    "A hexagon has six sides.",
    "A circle has no straight sides.",
    "The number zero is an important concept in mathematics.",
    "Prime numbers have exactly two positive divisors.",
    "The number 2 is the only even prime number.",
    "Pi is approximately 3.14159.",
    "A right angle measures 90 degrees.",
    "There are 60 seconds in a minute.",
    "There are 60 minutes in an hour.",
    "A kilometer contains 1,000 meters.",
    "A meter contains 100 centimeters.",
    "A standard chessboard has 64 squares.",
    "Chess is played between two players.",
    "A standard deck of playing cards contains 52 cards.",
    "The Earth takes about 365.25 days to orbit the Sun.",
    "Earth rotates once approximately every 24 hours.",
    "The Moon takes about a month to orbit Earth.",
    "Tides are strongly influenced by the gravitational pull of the Moon.",
    "The Northern and Southern Hemispheres have opposite seasons.",
    "Auroras occur when charged particles interact with Earth's atmosphere.",
    "A solar eclipse occurs when the Moon passes between Earth and the Sun.",
    "A lunar eclipse occurs when Earth passes between the Sun and Moon.",
    "Comets are made largely of ice, dust, and rocky material.",
    "Asteroids are rocky or metallic objects that orbit the Sun.",
    "Meteorites are space rocks that survive passage through an atmosphere and reach the ground.",
    "The International Space Station orbits Earth.",
    "Astronauts experience apparent weightlessness while orbiting Earth.",
    "Mars has two small moons called Phobos and Deimos.",
    "Jupiter has many known moons.",
    "Saturn is famous for its prominent ring system.",
    "Neptune is farther from the Sun than Uranus.",
    "The Sun is a star.",
    "Stars produce energy through nuclear processes.",
    "Our Sun is classified as a G-type main-sequence star.",
    "The universe contains billions of galaxies.",
    "Some galaxies have billions or even trillions of stars.",
    "Black holes have gravity strong enough that light cannot escape from within their event horizons.",
    "The observable universe is vastly larger than our Solar System.",
]

quiz_questions = {
    "What is the capital of France?": "Paris",
    "What is the largest planet in our Solar System?": "Jupiter",
    "What is the smallest planet in our Solar System?": "Mercury",
    "What planet is known as the Red Planet?": "Mars",
    "What is the name of Earth's natural satellite?": "The Moon",
    "How many planets are in our Solar System?": "8",
    "What star is at the center of our Solar System?": "The Sun",
    "What is the closest planet to the Sun?": "Mercury",
    "What is the hottest planet in our Solar System?": "Venus",
    "What is the largest ocean on Earth?": "Pacific Ocean",
    "What is the smallest ocean on Earth?": "Arctic Ocean",
    "What is the largest continent?": "Asia",
    "What is the smallest continent?": "Australia",
    "What is the largest country by land area?": "Russia",
    "What is the capital of Japan?": "Tokyo",
    "What is the capital of Nepal?": "Kathmandu",
    "What is the capital of India?": "New Delhi",
    "What is the capital of China?": "Beijing",
    "What is the capital of the United Kingdom?": "London",
    "What is the capital of the United States?": "Washington, D.C.",
    "What is the longest river in South America?": "Amazon River",
    "What is the largest hot desert in the world?": "Sahara Desert",
    "What is the highest mountain above sea level?": "Mount Everest",
    "Where is Mount Everest located?": "Nepal and China",
    "What is the deepest ocean trench?": "Mariana Trench",
    "What is the largest island in the world?": "Greenland",
    "Which country is shaped like a boot?": "Italy",
    "Which country has the Great Barrier Reef?": "Australia",
    "Which country is famous for the pyramids of Giza?": "Egypt",
    "Which continent is Egypt primarily located in?": "Africa",

    "How many continents are there?": "7",
    "How many oceans are there commonly recognized?": "5",
    "How many days are in a leap year?": "366",
    "How many days are in a standard year?": "365",
    "How many hours are in a day?": "24",
    "How many minutes are in an hour?": "60",
    "How many seconds are in a minute?": "60",
    "How many sides does a triangle have?": "3",
    "How many sides does a square have?": "4",
    "How many sides does a pentagon have?": "5",
    "How many sides does a hexagon have?": "6",
    "How many sides does an octagon have?": "8",
    "What is 5 + 7?": "12",
    "What is 10 × 10?": "100",
    "What is 100 ÷ 4?": "25",
    "What is 15 - 8?": "7",
    "What is 9 × 9?": "81",
    "What is the square root of 64?": "8",
    "What is the square root of 100?": "10",
    "What is 2 to the power of 5?": "32",
    "What is half of 50?": "25",
    "What is 25% of 100?": "25",
    "What is the value of pi approximately?": "3.14159",
    "How many degrees are in a right angle?": "90",
    "How many degrees are in a full circle?": "360",
    "What is the only even prime number?": "2",
    "What is the smallest prime number?": "2",
    "What is the next prime number after 7?": "11",
    "What is 12 × 12?": "144",
    "What is 144 ÷ 12?": "12",

    "What is the chemical symbol for water?": "H₂O",
    "What is the chemical symbol for oxygen?": "O",
    "What is the chemical symbol for hydrogen?": "H",
    "What is the chemical symbol for carbon?": "C",
    "What is the chemical symbol for gold?": "Au",
    "What is the chemical symbol for silver?": "Ag",
    "What is the chemical symbol for iron?": "Fe",
    "What is the chemical symbol for sodium?": "Na",
    "What is the chemical symbol for potassium?": "K",
    "What is the chemical symbol for calcium?": "Ca",
    "What is the most abundant gas in Earth's atmosphere?": "Nitrogen",
    "What gas do humans need to breathe?": "Oxygen",
    "What gas do plants absorb during photosynthesis?": "Carbon dioxide",
    "What gas do plants release during photosynthesis?": "Oxygen",
    "What is the pH of a neutral solution at standard conditions?": "7",
    "What is the center of an atom called?": "Nucleus",
    "What particle has a positive charge?": "Proton",
    "What particle has a negative charge?": "Electron",
    "What particle has no electric charge?": "Neutron",
    "What force pulls objects toward Earth?": "Gravity",
    "What is the freezing point of water in Celsius?": "0°C",
    "What is the boiling point of water at sea level in Celsius?": "100°C",
    "What is the hardest natural substance?": "Diamond",
    "What is the main element in diamonds?": "Carbon",
    "What metal is liquid at room temperature?": "Mercury",
    "What substance gives plants their green color?": "Chlorophyll",
    "What process do plants use to make food?": "Photosynthesis",
    "What is the study of matter and its properties called?": "Chemistry",
    "What is the study of living organisms called?": "Biology",
    "What is the study of forces and energy called?": "Physics",

    "How many bones does a typical adult human have?": "206",
    "What is the largest organ of the human body?": "Skin",
    "What is the largest bone in the human body?": "Femur",
    "What is the smallest bone in the human body?": "Stapes",
    "What organ pumps blood around the body?": "Heart",
    "What organ is primarily responsible for breathing?": "Lungs",
    "What organ controls most body functions?": "Brain",
    "What organ filters blood and produces urine?": "Kidneys",
    "What organ produces insulin?": "Pancreas",
    "What part of the body contains the brain?": "Skull",
    "How many chambers does the human heart have?": "4",
    "What cells carry oxygen in the blood?": "Red blood cells",
    "What cells help fight infections?": "White blood cells",
    "What is the basic unit of life?": "Cell",
    "What molecule carries genetic information?": "DNA",
    "What is the body's largest internal organ?": "Liver",
    "What sense organ is used for hearing?": "Ear",
    "What sense organ is used for vision?": "Eye",
    "What sense organ is used for smell?": "Nose",
    "What sense organ is used for taste?": "Tongue",

    "How many hearts does an octopus have?": "3",
    "What is the largest animal on Earth?": "Blue whale",
    "What is the fastest land animal?": "Cheetah",
    "What is the tallest land animal?": "Giraffe",
    "What is the largest land animal?": "African elephant",
    "What animal is known for its black and white stripes?": "Zebra",
    "What animal is known as the king of the jungle?": "Lion",
    "What animal is famous for changing its color?": "Chameleon",
    "What animal can fly backward?": "Hummingbird",
    "What animal is known for having a pouch?": "Kangaroo",
    "What is a baby dog called?": "Puppy",
    "What is a baby cat called?": "Kitten",
    "What is a baby horse called?": "Foal",
    "What is a baby cow called?": "Calf",
    "What is a group of lions called?": "Pride",
    "What is a group of wolves called?": "Pack",
    "What is a group of fish called?": "School",
    "What is a group of bees called?": "Swarm",
    "What do pandas mainly eat?": "Bamboo",
    "What do cows commonly produce that humans drink?": "Milk",
    "Which bird is often associated with wisdom?": "Owl",

    "Who was the first person to walk on the Moon?": "Neil Armstrong",
    "In which year did humans first land on the Moon?": "1969",
    "Who developed the theory of relativity?": "Albert Einstein",
    "Who developed the laws of motion?": "Isaac Newton",
    "Who is famous for discovering penicillin?": "Alexander Fleming",
    "Who invented the telephone?": "Alexander Graham Bell",
    "Who is commonly credited with inventing the practical light bulb?": "Thomas Edison",
    "Who developed the first successful airplane?": "The Wright brothers",
    "In which year was the first powered airplane flight?": "1903",
    "Which ancient civilization built the pyramids of Giza?": "Ancient Egyptians",
    "Which ancient city was buried by Mount Vesuvius?": "Pompeii",
    "Which empire built the Colosseum?": "Roman Empire",
    "Where did the Olympic Games originate?": "Ancient Greece",
    "Who was the first emperor of Rome?": "Augustus",
    "Who wrote the Declaration of Independence of the United States?": "Thomas Jefferson",
    "Who was the first president of the United States?": "George Washington",
    "Who was known as the Maid of Orléans?": "Joan of Arc",
    "Who was Mahatma Gandhi?": "An Indian independence leader",
    "Who was Nelson Mandela?": "A South African anti-apartheid leader",
    "Which ship famously sank in 1912?": "Titanic",

    "What language has the most native speakers?": "Mandarin Chinese",
    "What is the most widely spoken language by total speakers?": "English",
    "What language is primarily spoken in Brazil?": "Portuguese",
    "What language is primarily spoken in Spain?": "Spanish",
    "What language is primarily spoken in Germany?": "German",
    "What language is primarily spoken in France?": "French",
    "What is the most widely used alphabet in the world?": "Latin alphabet",
    "What is the opposite of 'hot'?": "Cold",
    "What is the opposite of 'ancient'?": "Modern",
    "What is a word with the opposite meaning called?": "Antonym",
    "What is a word with a similar meaning called?": "Synonym",
    "What is a word that sounds like another word but has a different meaning called?": "Homophone",
    "What punctuation mark ends a question?": "Question mark",
    "What punctuation mark shows strong emotion?": "Exclamation mark",
    "What is the plural of 'child'?": "Children",
    "What is the past tense of 'go'?": "Went",
    "What is the noun form of 'happy'?": "Happiness",
    "What is the opposite of 'increase'?": "Decrease",
    "What is a sentence's main action usually expressed by?": "Verb",
    "What type of word describes a noun?": "Adjective",

    "What is the largest mammal?": "Blue whale",
    "What is the largest bird?": "Ostrich",
    "What is the fastest bird in a dive?": "Peregrine falcon",
    "Which animal is famous for building dams?": "Beaver",
    "Which animal has a long trunk?": "Elephant",
    "Which animal has a very long neck?": "Giraffe",
    "Which animal is known for its shell?": "Turtle",
    "Which animal is famous for its ability to regenerate some body parts?": "Axolotl",
    "Which insect produces honey?": "Honey bee",
    "Which insect undergoes metamorphosis from caterpillar to adult?": "Butterfly",

    "What is the largest planet?": "Jupiter",
    "Which planet has the most prominent ring system?": "Saturn",
    "Which planet rotates on its side?": "Uranus",
    "Which planet has the Great Red Spot?": "Jupiter",
    "Which planet is farthest from the Sun among the eight planets?": "Neptune",
    "What is a light-year a measurement of?": "Distance",
    "What galaxy contains our Solar System?": "Milky Way",
    "What is the closest star to Earth?": "The Sun",
    "What is the closest star to the Sun?": "Proxima Centauri",
    "What causes a solar eclipse?": "The Moon passes between Earth and the Sun",
    "What causes a lunar eclipse?": "Earth passes between the Sun and Moon",
    "What are rocks from space that reach Earth's surface called?": "Meteorites",
    "What is the study of space called?": "Astronomy",
    "What is a large system of stars, gas, and dust called?": "Galaxy",
    "What object orbits a planet?": "Moon or satellite",

    "What is the capital of Australia?": "Canberra",
    "What is the capital of Canada?": "Ottawa",
    "What is the capital of Germany?": "Berlin",
    "What is the capital of Italy?": "Rome",
    "What is the capital of Spain?": "Madrid",
    "What is the capital of Russia?": "Moscow",
    "What is the capital of South Korea?": "Seoul",
    "What is the capital of Thailand?": "Bangkok",
    "What is the capital of Nepal?": "Kathmandu",
    "What is the capital of Brazil?": "Brasília",
    "What is the capital of Argentina?": "Buenos Aires",
    "What is the capital of Mexico?": "Mexico City",
    "What is the capital of Egypt?": "Cairo",
    "What is the capital of Kenya?": "Nairobi",
    "What is the capital of South Africa?": "Pretoria",
    "What is the capital of Turkey?": "Ankara",
    "What is the capital of Greece?": "Athens",
    "What is the capital of Portugal?": "Lisbon",
    "What is the capital of Norway?": "Oslo",
    "What is the capital of Sweden?": "Stockholm",

    "What does CPU stand for?": "Central Processing Unit",
    "What does RAM stand for?": "Random Access Memory",
    "What does ROM stand for?": "Read-Only Memory",
    "What does GPU stand for?": "Graphics Processing Unit",
    "What does HTML stand for?": "HyperText Markup Language",
    "What does CSS stand for?": "Cascading Style Sheets",
    "What does URL stand for?": "Uniform Resource Locator",
    "What does HTTP stand for?": "HyperText Transfer Protocol",
    "What does AI stand for?": "Artificial Intelligence",
    "What does ML stand for?": "Machine Learning",
    "What number system uses only 0 and 1?": "Binary",
    "How many bits are in a byte?": "8",
    "What language was Python named after?": "Monty Python",
    "Who created Python?": "Guido van Rossum",
    "What language was C++ developed from?": "C",
    "What is an algorithm?": "A step-by-step procedure for solving a problem",
    "What is a database used for?": "Storing and organizing data",
    "What does Wi-Fi allow devices to do?": "Communicate wirelessly over a network",
    "What is the internet?": "A global network of interconnected networks",
    "What is a computer program?": "A set of instructions for a computer",

    "How many players are on a soccer team on the field?": "11",
    "How many players are on a basketball team on the court?": "5",
    "How many rings are on the Olympic flag?": "5",
    "How many squares are on a chessboard?": "64",
    "How many players start a standard game of chess?": "2",
    "How many cards are in a standard deck?": "52",
    "What sport uses a bat and ball and wickets?": "Cricket",
    "What sport uses a racket and shuttlecock?": "Badminton",
    "What sport is played at Wimbledon?": "Tennis",
    "What sport is associated with the Super Bowl?": "American football",
    "What sport uses a puck?": "Ice hockey",
    "What sport uses clubs and holes?": "Golf",
    "What sport is Michael Jordan famous for?": "Basketball",
    "What sport is Lionel Messi famous for?": "Football",
    "What sport is Usain Bolt famous for?": "Sprinting",
    "What sport is Serena Williams famous for?": "Tennis",
    "What color card means a player is sent off in football?": "Red",
    "How many points is a touchdown worth before the extra point?": "6",
    "How many points is a basketball free throw worth?": "1",
    "How many bases are there in baseball?": "4",

    "What is the largest organ in the human body?": "Skin",
    "What is the largest internal organ?": "Liver",
    "Which organ produces bile?": "Liver",
    "Which organ stores urine?": "Bladder",
    "Which organ helps digest food?": "Stomach",
    "Where does most nutrient absorption occur?": "Small intestine",
    "What carries blood away from the heart?": "Arteries",
    "What carries blood toward the heart?": "Veins",
    "What pigment gives skin much of its color?": "Melanin",
    "What part of the eye controls how much light enters?": "Iris",
    "What part of the eye detects light?": "Retina",
    "What connects muscles to bones?": "Tendons",
    "What connects bones to other bones?": "Ligaments",
    "What protects the brain?": "Skull",
    "What protects the heart and lungs?": "Rib cage",

    "What is the currency of Japan?": "Yen",
    "What is the currency of the United States?": "US dollar",
    "What is the currency of the United Kingdom?": "Pound sterling",
    "What is the currency of India?": "Indian rupee",
    "What is the currency of Nepal?": "Nepalese rupee",
    "What is the currency of the European Union?": "Euro",
    "What is the currency of China?": "Yuan",
    "What is the currency of South Korea?": "Won",
    "What is the currency of Thailand?": "Baht",
    "What is the currency of Australia?": "Australian dollar",

    "What is the freezing point of water in Fahrenheit?": "32°F",
    "What is the boiling point of water in Fahrenheit at sea level?": "212°F",
    "How many meters are in a kilometer?": "1000",
    "How many centimeters are in a meter?": "100",
    "How many millimeters are in a centimeter?": "10",
    "How many grams are in a kilogram?": "1000",
    "How many milligrams are in a gram?": "1000",
    "How many centimeters are in a kilometer?": "100000",
    "How many degrees are in a straight angle?": "180",
    "What is the perimeter of a square with side length 5?": "20",

    "What is the name of the process when liquid becomes gas?": "Evaporation",
    "What is the process when gas becomes liquid?": "Condensation",
    "What is the process when liquid becomes solid?": "Freezing",
    "What is the process when solid becomes liquid?": "Melting",
    "What is the process when solid changes directly into gas?": "Sublimation",
    "What is the process when gas changes directly into solid?": "Deposition",
    "What is the movement of water through Earth's environment called?": "Water cycle",
    "What causes ocean tides mainly?": "Gravity of the Moon and Sun",
    "What layer of Earth do we live on?": "Crust",
    "What is the layer beneath Earth's crust called?": "Mantle",

    "What is the main source of energy for Earth?": "The Sun",
    "What renewable energy comes from moving air?": "Wind energy",
    "What renewable energy comes from sunlight?": "Solar energy",
    "What renewable energy comes from moving water?": "Hydroelectric energy",
    "What gas is a major greenhouse gas?": "Carbon dioxide",
    "What is the process of trees releasing water vapor called?": "Transpiration",
    "What is biodiversity?": "The variety of living organisms",
    "What is an ecosystem?": "A community of organisms and their environment",
    "What is a habitat?": "The natural home of an organism",
    "What is conservation?": "The protection and careful management of nature",

    "What is the name of the first month of the year?": "January",
    "What is the last month of the year?": "December",
    "How many months have 31 days?": "7",
    "How many months have 30 days?": "4",
    "What month has 28 days in a common year?": "February",
    "What day comes after Friday?": "Saturday",
    "What day comes before Monday?": "Sunday",
    "How many days are in a week?": "7",
    "How many months are in a year?": "12",
    "How many seasons are commonly recognized?": "4",

    "What is the opposite of north?": "South",
    "What is the opposite of east?": "West",
    "What instrument measures temperature?": "Thermometer",
    "What instrument measures atmospheric pressure?": "Barometer",
    "What instrument measures wind speed?": "Anemometer",
    "What instrument measures earthquakes?": "Seismometer",
    "What instrument is used to see distant stars?": "Telescope",
    "What instrument is used to see very small objects?": "Microscope",
    "What device measures time?": "Clock",
    "What device measures mass?": "Scale",

    "What is the name of Earth's outermost solid layer?": "Crust",
    "What is molten rock beneath Earth's surface called?": "Magma",
    "What is molten rock above Earth's surface called?": "Lava",
    "What is a mountain that can erupt called?": "Volcano",
    "What is shaking of Earth's crust called?": "Earthquake",
    "What is a large body of ice moving slowly over land called?": "Glacier",
    "What is a large body of salt water surrounded partly by land called?": "Sea",
    "What is land completely surrounded by water called?": "Island",
    "What is a narrow body of water connecting two larger bodies of water called?": "Strait",
    "What is land surrounded by water on three sides called?": "Peninsula",
}

class Helpful_Things:

    def Study_Tips(self):
        if "study_tips_choice" not in st.session_state:
            st.session_state.study_tips_choice = None

        st.title("Do you want a study tip?")
        _, tip_button, _ = st.columns([1, 2, 2])
        study_tips_button = tip_button.button("TIPS", use_container_width=True)

        if study_tips_button:
            st.session_state.study_tips_choice = r.choice(study_tips)

        if st.session_state.study_tips_choice is not None:
            _, tip, _ = st.columns([1, 7, 1])
            tip.write(st.session_state.study_tips_choice)

        st.divider()

    def Random_Facts(self):

        if "random_facts_choice" not in st.session_state:
            st.session_state.random_facts_choice = None

        st.title("Do you want a random fact?")
        _, fact_button, _ = st.columns([1, 2, 2])
        random_facts_button = fact_button.button("Random Fact", use_container_width=True)

        if random_facts_button:
            st.session_state.random_facts_choice = r.choice(random_facts)

        if st.session_state.random_facts_choice is not None:
            _, fact, _ = st.columns([1, 7, 1])
            fact.write(st.session_state.random_facts_choice)

        st.divider()

    def Random_Quiz(self):

        if "random_quiz_choice" not in st.session_state:
            st.session_state.random_quiz_choice = None


        st.title("Do you want a random quiz?")

        _, quiz_button, _ = st.columns([1, 2, 2])

        random_quiz_button = quiz_button.button(
            "Random Quiz",
            use_container_width=True
        )

        if random_quiz_button:
            st.session_state.random_quiz_choice = r.choice(
                list(quiz_questions.keys())
            )

        if st.session_state.random_quiz_choice is not None:

            _, quiz, _ = st.columns([1, 7, 1])
            quiz.write(st.session_state.random_quiz_choice)

            answer_quiz = st.text_input("Enter your answer:")

            if answer_quiz:
                if answer_quiz.lower() == quiz_questions[st.session_state.random_quiz_choice].lower():
                    st.success("Right answer!")

                else:
                    st.warning("Wrong answer!")

        st.divider()

obj_helpful_things = Helpful_Things()
obj_helpful_things.Study_Tips()
obj_helpful_things.Random_Facts()
obj_helpful_things.Random_Quiz()